Spec fixes
rpiml/okcollege-college-training-preprocessor pull request #12
Opened 2016-12-18 06:58 UTC by jko0531

2016-12-18 07:17 UTC, jko0531 commented
The updated csv files (colleges.csv, college_labels.csv) can be found in the spec-fixes branch in assets folder in okcollege-dev

2016-12-20 20:42 UTC, seveibar requested changes

2016-12-20 20:42 UTC, seveibar commented on college_preprocessor.py
>  import pika
A descriptive comment at the top of the module explaining the general purpose of the module and it's process would be useful here, [here's an example from the survey preprocessor](https://github.com/rpiml/survey-preprocessor/blob/master/src/parse.js)

2016-12-20 20:42 UTC, seveibar commented
does this fix #4 ?

2016-12-20 20:44 UTC, seveibar commented
Other than the descriptive comment, this is looking pretty good.

2016-12-20 21:07 UTC, jowlee commented on college_preprocessor.py
> +	return 0
Does not having a value that matches the choices mean that the school is 'least selective' or that it wasn't included. If it wasn't included, we should probably modify the default to be a unique number like -1 or shift the other values up one value.

2016-12-20 21:08 UTC, jowlee commented on college_preprocessor.py
> +	return 0
Does not having a value for SAT or ACT imply that the school accepts neither? If not then it should be return a unique number.

2016-12-20 21:10 UTC, jowlee commented on college_preprocessor.py
> +    df.fillna(0, inplace=True)
If 0 is the default value for N/A then it should not associated with another value like 'No' or 'least-selective'

2016-12-20 23:16 UTC, jko0531 commented on college_preprocessor.py
> +	return 0
good point, I've changed all N/A values in categories to be -1.

2016-12-20 23:16 UTC, jko0531 commented on college_preprocessor.py
> +    df.fillna(0, inplace=True)
After making the changes above, this won't be an issue anymore

2016-12-20 23:25 UTC, jko0531 commented
Not sure where the vendor folder came from...is that a side effect from the docker-compose?

2016-12-28 15:38 UTC, seveibar commented
I also don't know, but you'll have to do an interactive rebase and remove it from the commit before we merge or else our history will get messed up here :/

2016-12-28 15:39 UTC, seveibar commented
(after the interactive rebase you'll have to force push btw)

2016-12-29 03:29 UTC, jko0531 commented
not sure if I did the rebase stuff right...but college_preprocessor.py looks good now, with the vendor stuff removed.

2016-12-29 05:52 UTC, seveibar commented
looks right to me

2016-12-29 05:53 UTC, seveibar approved these changes

2016-12-29 05:53 UTC, merged

2016-12-29 05:54 UTC, seveibar commented
i looked into it a bit btw and yes the vendor stuff is created by docker-compose, it basically caches the pip stuff, just add vendor to the .gitignore so it's not accidentally committed in the future